<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Markup;
use Drupal;
use Drupal\node\NodeInterface;

/**
 * Implements hook_help().
 */
function curso_module_help($route_name, RouteMatchInterface $route_match) {
  $moduleHandler = Drupal::service('extension.list.module');
  $modulePath = $moduleHandler->getPath('curso_module');
  $imageUrl = base_path() . $modulePath . '/images/search.png';

  switch ($route_name) {
    case 'help.page.curso_module':
      $output = '
      <img src="'.$imageUrl.'" alt="Logo del modulo curso" />
      <p>Esta es la pagina de ayuda del modulo curso</p>
      <p>Este modulo permite gestionar curso</p>';
      return $output;
      //return Markup::create($output);
    break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * @param Drupal\Core\Entity\EntityInterface $entity
 */
function curso_module_node_insert(NodeInterface $node) {
  $messenger = Drupal::service('messenger');
  $messenger->addError('drupal esta llamando al hook insert');
}

/**
 * Implements hook_ENTITY_TYPE_update().
 *
 * @param Drupal\Core\Entity\EntityInterface $entity
 */
function curso_module_node_update(NodeInterface $node) {
  $messenger = Drupal::service('messenger');
  $messenger->addError('drupal esta llamando al hook update');

}
