<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Markup;
use Drupal;
use Drupal\node\NodeInterface;
use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function curso_module_help($route_name, RouteMatchInterface $route_match) {
  $moduleHandler = Drupal::service('extension.list.module');
  $modulePath = $moduleHandler->getPath('curso_module');
  $imageUrl = base_path() . $modulePath . '/images/search.png';

  switch ($route_name) {
    case 'help.page.curso_module':
      $output = '
      <img src="'.$imageUrl.'" alt="Logo del modulo curso" />
      <p>Esta es la pagina de ayuda del modulo curso</p>
      <p>Este modulo permite gestionar curso</p>';
      return $output;
      //return Markup::create($output);
    break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * @param Drupal\Core\Entity\EntityInterface $entity
 */
function curso_module_node_insert(NodeInterface $node) {
  $messenger = Drupal::service('messenger');
  $messenger->addError('drupal esta llamando al hook insert');
}

/**
 * Implements hook_ENTITY_TYPE_update().
 *
 * @param Drupal\Core\Entity\EntityInterface $entity
 */
function curso_module_node_update(NodeInterface $node) {
  $messenger = Drupal::service('messenger');
  $messenger->addError('drupal esta llamando al hook update');

}


/**
 * interface hook_theme($existing, $type, $theme, $path)
 */
function curso_module_theme($existing, $type, $theme, $path) {
  return [
    'curso_plantilla' => [
      'variables' => ['etiqueta' => NULL, 'tipo' => NULL]
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function curso_module_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /*if ($form_id == 'curso_module_form') {
    $form['mensaje']['#required'] = true;
    $form['apellido']['#required'] = false;
    //dd($form);
  }

  if ($form_id == 'node_article_form') {
    dpm('Alterando el formulario de articulo');
  }*/

  switch ($form_id) {
    case 'node_article_form':
      dpm('Alterando el formulario de articulo');
      break;
    case 'curso_module_form':
      $form['mensaje']['#required'] = true;
      $form['apellido']['#required'] = false;
      break;
  }
}
/**
 * Implements hook_form_FORM_ID_alter().
 */
function curso_module_form_curso_module_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['mensaje']['#required'] = true;
  $form['apellido']['#required'] = false;
}
